foo

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -67,21 +67,20 @@ runs:
     - run: |
         # Perform regression testing if tests exist
         if ls $REGRESSION_TEST_DIR/*.xml 1> /dev/null 2>&1 ; then
-          echo "FOO"
           # Update info in examples
           sed -i "s/\[IM_VERSION\]/$IM_VERSION/g" $REGRESSION_TEST_DIR/*.xml
 
-        #   # Run VALID regression tests
-        #   ${{ github.action_path }}/validate.sh "${{inputs.test_dir}}/*_VALID.xml" "${{inputs.schemas}} /tmp/${{inputs.pds4_im_version}}/*.xsd" "${{inputs.schematrons}} /tmp/${{inputs.pds4_im_version}}/*.sch" "false"
-        #   valid_exit=$?
+          # Run VALID regression tests
+          ${{ github.action_path }}/validate.sh "${{inputs.test_dir}}/*_VALID.xml" "${{inputs.schemas}} /tmp/${{inputs.pds4_im_version}}/*.xsd" "${{inputs.schematrons}} /tmp/${{inputs.pds4_im_version}}/*.sch" "false"
+          valid_exit=$?
 
-        #   # Run FAIL regression tests
-        #   ${{ github.action_path }}/validate.sh "${{inputs.test_dir}}/*_FAIL.xml" "${{inputs.schemas}} /tmp/${{inputs.pds4_im_version}}/*.xsd" "${{inputs.schematrons}} /tmp/${{inputs.pds4_im_version}}/*.sch" "true"
-        #   fail_exit=$?
+          # Run FAIL regression tests
+          ${{ github.action_path }}/validate.sh "${{inputs.test_dir}}/*_FAIL.xml" "${{inputs.schemas}} /tmp/${{inputs.pds4_im_version}}/*.xsd" "${{inputs.schematrons}} /tmp/${{inputs.pds4_im_version}}/*.sch" "true"
+          fail_exit=$?
 
-        #   exit $valid_exit && $fail_exit
-        # else
-        #   echo 'Regression Tests do not exist, skipping'
-        #   exit 0
+          exit $valid_exit && $fail_exit
+        else
+          echo 'Regression Tests do not exist, skipping'
+          exit 0
         fi
       shell: bash
